eclipse/xtext-maven

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
> [#3] Upgrade to Tycho 0.25.0

- Jenkinsfile
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/java-lang-bi-ref/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/maven-config/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
- org.eclipse.xtext.parent/pom.xml
- org.eclipse.xtext.xtext/pom.xml
- pom.xml
Repair Xtext Maven Module
* make the module build again
* fix tests
> Repair Xtext Maven Module

- Jenkinsfile
- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
- org.eclipse.xtext.parent/pom.xml
- pom.xml
Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>
> [releng] use build/maven-repository as deploy target

- org.eclipse.xtext.maven.plugin/.classpath
- org.eclipse.xtext.maven.plugin/.settings/org.eclipse.jdt.core.prefs
> switch java 6 -> java 8

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
> update to tycho 1.0.0

- org.eclipse.xtext.maven.plugin/pom.xml
> repaired publish build

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/java-lang-bi-ref/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/maven-config/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
> use 2.14 as version

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
update to tycho 1.1.0 https://github.com/eclipse/xtext/issues/1172
> update to tycho 1.1.0

- org.eclipse.xtext.maven.plugin/.classpath
fixed m2e settings for photon https://github.com/eclipse/xtext/issues/1180
> fixed m2e settings for photon

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> refactored branch_url_segment to prepare [eclipse/xtext#1214]

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
> [eclipse/xtext#1225] Update to Tycho 1.2.0

- org.eclipse.xtext.maven.parent/pom.xml
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
> Just updated my email and organization in parent pom

- org.eclipse.xtext.maven.plugin/pom.xml
which are inherited from the parent pom
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
> Don't repeat groupId and version

- org.eclipse.xtext.maven.parent/pom.xml
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>
> Add contact data in parent pom and gradle files.

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/pom.xml
[eclipse/xtext#1231] fixed jdt and platform versions
> [eclipse/xtext#1231] fixed jdt and platform versions

- org.eclipse.xtext.maven.parent/pom.xml
[eclipse/xtext#1263] Pinned EMF Version to 2.12
> [eclipse/xtext#1263] Pinned EMF Version to 2.12

- org.eclipse.xtext.maven.parent/pom.xml
> [#47] Upgrade maven-javadoc-plugin version to 3.0.1

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/java-lang-bi-ref/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/maven-config/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/pom.xml
> updated versions to 2.16.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
Signed-off-by: Prajwal Gowda <pgowda@itemis.de>
> [release] version 2.16.0.M1

- org.eclipse.xtext.maven.parent/pom.xml
> Use TypeFox Jenkins URL for lsp4j

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/java-lang-bi-ref/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/maven-config/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/pom.xml
> change version 2.16.0 -> 2.17.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
[eclipse/xtext#1322] switched to tycho 1.3.0
> [eclipse/xtext#1322] switched to tycho 1.3.0

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
> [#59] fixed broken tests

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
> [eclipse/xtext#1249] use bom for version management

- org.eclipse.xtext.maven.parent/pom.xml
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
> [https://github.com/eclipse/xtext/issues/1330] Update developers section

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/aggregate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/clustering/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/java-lang-bi-ref/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/maven-config/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-source/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/purexbase/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf.edit/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf.edit/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf/pom.xml
Move many common stuff to IT test's parent POM and clean up child projects.
> Refactoring integration tests

- Jenkinsfile
> removed duplicate -DJENKINS_URL

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
[eclipse/xtext#1414] prepared master for version 2.18.0 
> [eclipse/xtext#1414] prepared master for version 2.18.0

- README.md
- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
[#74] use https to access typefox jenkins
> [#74] use https to access typefox jenkins

- org.eclipse.xtext.maven.parent/pom.xml
Signed-off-by: Holger Schill <Holger.Schill@itemis.de>
> Remove IDEA since the support has been dropped.

- org.eclipse.xtext.maven.parent/pom.xml
> replaced tf jenkins with ci.eclipse.org/xtext for lsp4j

- CBI.Jenkinsfile
- also disable concurrent builds
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=544006#c7
> [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
[eclipse/xtext#1422] update to tycho 1.4.0
> [eclipse/xtext#1422] update to tycho 1.4.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
> [eclipse/xtext#1474] Prepare Master for 2.19

- Jenkinsfile
- org.eclipse.xtext.maven.plugin/pom.xml
> [eclipse/xtext#1384] Convert Jenkinsfile to declarative pipeline

- org.eclipse.xtext.maven.parent/pom.xml
> bumped some maven plugins

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
> [eclipse/xtext#1507] Adjust lsp4j upstream URL / Use env.JENKINS_URL

- org.eclipse.xtext.maven.parent/pom.xml
> bumped org.eclipse.xtext.maven.parent/pom.xml

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Set version to 2.20.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
[eclipse/xtext#1553] update to tycho 1.5.0
> [eclipse/xtext#1553] update to tycho 1.5.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
[eclipse/xtext#1566] update to tycho 1.5.1
> [eclipse/xtext#1566] update to tycho 1.5.1

- org.eclipse.xtext.maven.parent/pom.xml
> bumped maven-source-plugin

- org.eclipse.xtext.maven.plugin/.classpath
[eclipse/xtext#1573] Do not share output folders between mvn and Eclipse
> [eclipse/xtext#1573] Do not share output folders between mvn and Eclipse

- .gitignore
> added bin-test to gitignore

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.21.0

- org.eclipse.xtext.maven.parent/pom.xml
> updated maven-source-plugin

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
[eclipse/xtext#1282] update to EMF 2.20
> [eclipse/xtext#1282] update to EMF 2.20

- Jenkinsfile
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf.edit/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf/pom.xml
> [#116] archive test results

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
[eclipse/xtext#1643] update to tycho 1.6.0
> [eclipse/xtext#1643] update to tycho 1.6.0

- Contribute.md
- LICENSE
- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextGeneratorMojo.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/ClusteringConfig.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/Language.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/MavenLog4JConfigurator.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/MavenStandaloneBuilderModule.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/OutputConfiguration.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/ProjectMapping.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/XtextGenerateMojo.java
- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/XtextTestGenerateMojo.java
- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
This PR changes the code license from EPL 1.0 to EPL 2.0 and adds a Contribute.md file.
see https://github.com/eclipse/xtext/issues/1176
> EPL1.0 -> EPL2.0 and contribute.md

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.22.0

- org.eclipse.xtext.maven.plugin/pom.xml
> removed old gen

- org.eclipse.xtext.maven.parent/pom.xml
> bumped maven javadoc plugin

- org.eclipse.xtext.maven.parent/pom.xml
maven-antrun-plugin to 3.0.0
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
> [https://github.com/eclipse/xtext/issues/1742] Update

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
> [https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.23.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.24.0

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/output-per-goal/pom.xml
update to junit 4.13.1 for test
> update to junit 4.13.1 for test

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
[#20] updated and cleaned up test deps
Fixes #20
> [#20] updated and cleaned up test deps

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.25.0

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.26.0

- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
added workaround for sporadic resolver race problem 
https://issues.apache.org/jira/browse/MRESOLVER-153
> added workaround for sporadic resolver race problem 

- org.eclipse.xtext.maven.parent/pom.xml
> bump maven-javadoc-plugin

- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
removed workaround for sporadic resolver race problem
https://issues.apache.org/jira/browse/MRESOLVER-153
> removed workaround for sporadic resolver race problem

- org.eclipse.xtext.maven.parent/pom.xml
use newer maven-javadoc-plugin
> use newer maven-javadoc-plugin

- org.eclipse.xtext.maven.parent/pom.xml
> bump maven-plugin-plugin

- NOTICE.md
[eclipse/xtext#2020] update to classgraph 4.8.138
> [eclipse/xtext#2020] update to classgraph 4.8.138

- org.eclipse.xtext.maven.parent/pom.xml
bump maven-compiler-plugin 3.8.1 -> 3.9.0
> bump maven-compiler-plugin 3.8.1 -> 3.9.0

- org.eclipse.xtext.maven.parent/pom.xml
> bump maven-compiler-plugin

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.27.0

- org.eclipse.xtext.maven.parent/pom.xml
bump maven-compiler-plugin to 3.10.1
> bump maven-compiler-plugin to 3.10.1

- org.eclipse.xtext.maven.plugin/pom.xml
[eclipse/xtext#2028] switch to reload4j
> [eclipse/xtext#2028] switch to reload4j

- org.eclipse.xtext.maven.plugin/pom.xml
bumped maven-verifier to 1.8.0
> bumped maven-verifier to 1.8.0

- org.eclipse.xtext.maven.parent/pom.xml
> bumped maven antrun plugin

- org.eclipse.xtext.maven.parent/pom.xml
bump maven-javadoc-plugin to 3.4.0
> bump maven-javadoc-plugin to 3.4.0

- .settings/org.eclipse.core.resources.prefs
added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs
> added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs

- org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
fix maven-verifier deprecations
> fix maven-verifier deprecations

- NOTICE.md
[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06
> [eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.28.0

- org.eclipse.xtext.maven.parent/pom.xml
bump maven-enforcer-plugin to 3.1.0
> bump maven-enforcer-plugin to 3.1.0

- NOTICE.md
[eclipse/xtext#2071] update to orbit 2022-09
> [eclipse/xtext#2071] update to orbit 2022-09

- org.eclipse.xtext.maven.parent/pom.xml
bump maven-javadoc-plugin to 3.4.1
> bump maven-javadoc-plugin to 3.4.1

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.29.0

- NOTICE.md
[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
> [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

- Jenkinsfile
- org.eclipse.xtext.maven.parent/org.eclipse.xtext.parent.launch
- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/.classpath
- org.eclipse.xtext.maven.plugin/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf/pom.xml
[eclipse/xtext#1982] support for java 17
> [eclipse/xtext#1982] support for java 17

- NOTICE.md
[eclipse/xtext#2104] update to asm 9.4
> [eclipse/xtext#2104] update to asm 9.4

- org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextGeneratorMojo.java
switch compiler level default to 11
> switch compiler level default to 11

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf/pom.xml
[#186] run all tests at least with java 11
> [#186] run all tests at least with java 11

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf/model/a.xcore
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf/model/a.xcore
[eclipse/xtext#2127] Update to EMF 2022-03 (2.29.0)
> [eclipse/xtext#2127] Update to EMF 2022-03 (2.29.0)

- org.eclipse.xtext.maven.parent/pom.xml
bump maven-plugin-plugin 3.7.1
> bump maven-plugin-plugin 3.7.1

- org.eclipse.xtext.maven.parent/pom.xml
> bump maven-enforcer-plugin

- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-auto-mapping/sample-auto.emf/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-mapping/sample.emf/pom.xml
pin more common.types versions to avoid problems with range of death in xcore
> pin more common.types versions to avoid problems with range of death in xcore

- org.eclipse.xtext.maven.parent/pom.xml
- org.eclipse.xtext.maven.plugin/pom.xml
- org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
> [releng] Update Xtext version to 2.31.0
